### ISSUE TITLE
Join Neo4j community

### ISSUE THREAD

**Issue by ikwattro** [martin-helmich/graphpizer-cli#1]
Hello !!!

Thanks for this library, I'll test it as soon as I can.

In the meantime I invite you to join the neo4j software analytics google group : https://groups.google.com/group/graph-software-analytics

and the Neo4j public Slack Channel : http://neo4j-users-slack-invite.herokuapp.com/

In both channels you'll be able to discuss Cypher optimization and present your project.

Cheers from a Neo4j and PHP addict !

**Comment by martin-helmich** [comment]
Thanks for the invite, the group looks really interesting. I'll stop by when get the chance!
